import { Metadata } from "next";
import { Inter, Caveat, Playfair_Display } from "next/font/google";
import localFont from "next/font/local";

export const inter = Inter({
  weight: ["300", "400", "500"],
  style: ["normal", "normal", "normal"],
  subsets: ["latin"],
});

export const caviat = Caveat({ subsets: ["latin"] });

export const playfair = Playfair_Display({ weight: "500", subsets: ["latin"] });

export const loRes = localFont({ src: "./fonts/lores.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
